### ISSUE TITLE
quantifyGenes function 

### ISSUE THREAD

**Issue by Alexadol** [MalteThodberg/CAGEfightR#10]
Hi Malte,
I have some question about features of quantifyGenes() function. Can you please explain exact mechanism of this action? The manual says  "TC expression can be summed up within genes to obtain a gene-level expression matrix". i'd like to know whether expression of TCs located in the promoter and proximal regions of genes are also taken into account? And what about antisense TCs? 
Best regards, 
Alexa

**Comment by MalteThodberg** [comment]
It's very simple, CAGEfightR just calls the rowsum()-function on the counts using whatever column holds gene IDs. So you can basically put whatever you want in that column, and it will simply sum of TCs for each annotated gene.
If you use assignGeneID() with default settings, this will include all sense-direction TCs within the gene + TCs upstream of the annotated TSSs.

**Comment by Alexadol** [comment]
Ok, it's clear now! 
Thank you for your response!
