### ISSUE TITLE
quantifyCTSSs error

### ISSUE THREAD

**Issue by lananh-ngn** [MalteThodberg/CAGEfightR#14]
Hello developers,
I tried relauching some command lines that were working few months prior but now, the quantifyCTSSs is giving me this error. 
`Checking design...
Checking supplied genome compatibility...
Iterating over 1 genomic tiles in 1 samples using 10 worker(s)...
Importing CTSSs from plus strand...
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error: 'ranges' must have the length of the object to construct`
Is there a way to work around this problem?
Thank you very much in advance,
Best regards,
Lan Anh

**Comment by MalteThodberg** [comment]
This is strange: That part of CAGEfightR has not been updated recently.

Could be some upstream Bioconductor causing the issues: Did you recently update your Bioconductor packages?

**Comment by lananh-ngn** [comment]
Thank you for the answer. I forgot about me posting here. The error was not reproducible on another computer so I think that there is a problem with the Bioconductor packages.
