### ISSUE TITLE
Loading of CTSS/bigWig files

### ISSUE THREAD

**Issue by KevinMenden** [MalteThodberg/CAGEfightR#2]
Hi,

I'm very interested in using the CAGEfightR package for analysis of our CAGE-seq data, basically as alternative to CAGEr.

However, as has been pointed out in the other issue, it is quite inconvenient to use BigWig files as input. I already have CTSS files (generated by CAGEr), and would like to just load.

I was not successfull in transforming bed files into BigWig format using rtracklayer, but tried to use deepTools bamCoverage instead. Here's the command I used to generate BigWig files from BAM:

`bamCoverage -b frontal/00116_fro.bam --binSize 1 -p 8 --filterRNAstrand forward -o 00116_fro_forward2.bw`

Similar for the reverse strand. I assumed that I have to use a binSize of 1. However, when trying to load this into CAGEfightR, I get the following error:

`Merging strands...
Error in asMethod(object) : 
  all the ranges in the object to coerce to GPos must have a width of 1`

Could you help me with that? How can I succesfully create those bigWig files in suitable format for CAGEfightR?

I would really appreciate some help - the package looks really quite promising :) 

Cheers,
Kevin

**Comment by bkaczkowski** [comment]
Hi Kevin, 
I had same issue and this is how I solved it. I share the code in case it is helpful.

#' Convers CTSS bed file to  BigWig
#'
#' @param ctss_file path to ctss.bed file
#' @param genomeInfo genome info file created e.g. by "rtracklayer::SeqinfoForUCSCGenome("hg38")"
#' @return The function writes two files, one for each strand, (".plus.bw" and ".minus.bw"), in the same directory as the original file
#' @importFrom GenomicRanges GRanges
#' @importFrom rtracklayer import export
#' @export
convert_ctss_to_bigwig = function( ctss_file, genomeInfo ) {
  tpm_bed = rtracklayer::import(ctss_file)
  tpm_bed = GenomicRanges::GRanges(tpm_bed , seqinfo =  genomeInfo)
  tpm_bed_plus  = tpm_bed[ tpm_bed@strand == "+", ]
  tpm_bed_minus = tpm_bed[ tpm_bed@strand == "-", ]
  rtracklayer::export(object = tpm_bed_plus , paste(ctss_file ,   ".plus.bw" , sep = "")  , format = "BigWig" )
  rtracklayer::export(object = tpm_bed_minus, paste(ctss_file ,  ".minus.bw" , sep = "")  , format = "BigWig" )
}

**Comment by KevinMenden** [comment]
Hi,

thanks a lot, I'll give it a shot!

**Comment by KevinMenden** [comment]
Hi,

the workaround from @bkaczkowski  worked. I loaded the CTSS files into CAGEr, exported it to BED, loaded it back into R and transformed it to BigWig to being able to parse it with CAGEfightR.
Note a nice workaround but the only way it works currently. Would be nice to have more parsing functionality :-)

I have a separate problem now but will oben a new issue for this...

**Comment by MalteThodberg** [comment]
@bkaczkowski got here before me! Good to see it is working!

I saw some reports of the G-bias correction from CAGEr not working properly, probably good to be aware of if you are using that package: https://support.bioconductor.org/p/122737/ 

While we are waiting for the paper to be accepted, I'm working on the next update for CAGEfightR, which will include more functionality for manipulation of CTSSs in BigWig/BED/bedGraphs files. Hopefully I should be able to push it during the next release cycle of Bioconductor!
