### ISSUE TITLE
'Problem too large' error when doing TMP normalization

### ISSUE THREAD

**Issue by KevinMenden** [MalteThodberg/CAGEfightR#3]
Hi,

after loading my data into CAGEfightR, I want to do TPM normalization but get the following error:

`Calculating library sizes...
Calculating TPM...
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105`

The information about the CTSS object is the following:
`### CTSS summary ###
Number of samples: 50
Number of CTSSs: 44.66 millions
Sparsity: 100 %
Final object size: 1.67 GB`

It works for 40 samples, but not for 50. Apparently the file is too large. Which shouldn't be a problem as CAGEfightR was developed for large problems - so maybe there's another solution?

Maybe as reference, I'm running this on a machine with 750 GB of RAM.

@MalteThodberg help would be highly appreciated :) 

Best,
Kevin

**Comment by MalteThodberg** [comment]
That looks very strange indeed. 50 million CTSSs * 50 samples shouldn't be big enough to cause issues.

It looks to be extremely sparse though, at almost 100%?

**Comment by KevinMenden** [comment]
Okay, I'm not sure where the sparsity comes from. Maybe it's an issue with how I create the BigWig files (CTSS --> Bed --> BigWig).

In fact, I've had a quick look at the Bed-files that I exported with CAGEr. They look pretty sparse.
Maybe that's the issue .... I'll manually convert the CTSS to Bed files, create BigWigs, load them to CAGEfightR and see what happens. 

Thanks for the hint!

**Comment by MalteThodberg** [comment]
I'm not an expert on CAGEr, but there was some talk of some of the G-bias correction behaving incorrectly: https://support.bioconductor.org/p/122737/ 

Otherwise, it's hard for me to trouble shoot without the actual files.

What you could do is load the Matrix package itself, and see if you can perform the basic summaries on the assay(CTSSs, "counts") matrix, like rowSums and colSums.

**Comment by KevinMenden** [comment]
Alright, thanks!

I'll first try to generate the bed files manually. A short script should do the trick - just have to add a few columns to the ctss file. Then I don't have to use CTSS and can basically directly load the data to CAGEfightR.

I'll report back here how that worked out.

**Comment by KevinMenden** [comment]
Okay, this worked. Apparently the sparsity was the problem. 

The object still has a 95.38% sparsity, but at least the TPM calculation worked without a problem.

Thanks for the help!

**Comment by MalteThodberg** [comment]
Good to hear!

95 % sparsity sounds reasonable!
