### ISSUE TITLE
Error running quantifyCTSSs

### ISSUE THREAD

**Issue by matthew-valentine** [MalteThodberg/CAGEfightR#5]
Hi there,

I've just tried to run quantifyCTSSs on my bigwig files but I keep encountering an error. It seems that after merging the plus and minus strands, when it attempts to convert to GPos it is unable to. The error mentions "Error in asMethod(object) : all the ranges in the object to coerce to GPos must have a width of 1", but when I check the ranges myself, the smallest width is 2, so I am unsure why I am getting this error.

Best,

Matthew

**Comment by MalteThodberg** [comment]
Hello Matthew,

Exciting to see you are using CAGEfightR.

For CAGEfightR to work properly,  the BigWig-files should contain only single-bp ranges, e.g. 1 bp has one associated count. So the width of all ranges in the BigWig-files should be  exactly 1.

**Comment by matthew-valentine** [comment]
Thanks for the help! I was using bigwig files generated from clusters rather than single bp CAGE tags, so that's where I was going wrong.
