### ISSUE TITLE
'seqnames must have the length of the object to construct (1) or length 1'  Error

### ISSUE THREAD

**Issue by smooshington** [MalteThodberg/CAGEfightR#6]
I'm trying out CagefighteR for some CAGE data I recently received and I'm getting this following error that I don't understand how to fix:

I manage to read in files and build the CTSS object fine, but when trying to build a TSS or Enhancer object:

```
> CTSSs <- quantifyCTSSs(plusStrand = bw_plus,
+                        minusStrand = bw_minus,
+                        genome = genomeInfo,
+                        design = design)
Checking design...
Checking supplied genome compatibility...
Iterating over 1 genomic tiles in 4 samples using 1 worker(s)...
Importing CTSSs from plus strand...
Importing CTSSs from minus strand...
Merging strands...
Formatting output...
### CTSS summary ###
Number of samples: 4
Number of CTSSs: 13.08 millions
Sparsity: 66.27 %
Type of rowRanges: StitchedGPos
Final object size: 297 MB

> CTSSs
class: RangedSummarizedExperiment 
dim: 13078283 4 
metadata(0):
assays(1): counts
rownames: NULL
rowData names(0):
colnames(4): N04 N07 N05 N08
colData names(3): Name BigWigPlus BigWigMinus

> rowRanges(CTSSs)
StitchedGPos object with 13078283 positions and 0 metadata columns:
             seqnames       pos strand
                <Rle> <integer>  <Rle>
         [1]     chr1     30819      +
         [2]     chr1     30824      +
         [3]     chr1    155593      +
         [4]     chr1    164184      +
         [5]     chr1    184470      +
         ...      ...       ...    ...
  [13078279]     chrY  26664968      -
  [13078280]     chrY  26670670      -
  [13078281]     chrY  56734829      -
  [13078282]     chrY  56734830      -
  [13078283]     chrY  56735617      -
  -------
  seqinfo: 595 sequences from hg38 genome

CTSSs <- CTSSs %>%             
  calcTPM() %>%              
  calcPooled()   


> TSSs <- quickTSSs(CTSSs)
 - Running calcTPM and calcPooled:
Calculating library sizes...
Calculating TPM...

 - Running clusterUnidirectionally:
Splitting by strand...
Slice-reduce to find clusters...
Calculating statistics...
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or length 1
```

Same error comes up following the vignette using clusterUnidirectionally.

Is it a problem with the input files? The ranges are all length one and I used your conversion tool (convertBED2BigWig) to make them. The original files are six column BED files in format:

`` 
chr1    20193   20194 chr1:20193..20194,-       1 -    
``

Did I mess up making the files somehow?

**Comment by MalteThodberg** [comment]
Cool to see you considering CAGEfightR!

I have indeed not seen that error before - might be a new bug.

There's a few things you could do to help me figure out what's going on:

- Can you run the example code from the functions in question? (just try and copy-paste and see if it runs without errors)
- Can you run the code from the vignette?
- quickTSSs is a wrapper function: Can you run calcTPM, calcPooled and clusterUnidirectionally on their own?

**Comment by smooshington** [comment]
Hey, sorry for the trouble. I don't know exactly why, but I redid the conversion from BED to BigWig and now all the files work and the quickTSS / clusterUnidirectionally  etc. pass normally.
