### ISSUE TITLE
'The 2 combined objects have no sequence levels in common' warning while running quantifyCTSSs

### ISSUE THREAD

**Issue by NexentaEL** [MalteThodberg/CAGEfightR#7]
Hi Malte,

thank you for the useful package. I have a warning while running quantifyCTSSs function:
```
> CTSSs <- quantifyCTSSs(plusStrand = bwPlus,
+                        minusStrand = bwMinus,
+                        genome = seqinfo(bsg),
+                        design = design)
Checking design...
Checking supplied genome compatibility...
Iterating over 1 genomic tiles in 6 samples using 4 worker(s)...
Importing CTSSs from plus strand...
Importing CTSSs from minus strand...
Merging strands...
Formatting output...
### CTSS summary ###
Number of samples: 6
Number of CTSSs: 0.3046 millions
Sparsity: 66.3 %
Type of rowRanges: StitchedGPos
Final object size: 8.95 MB
Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```

BigWig files were obtained by experimental function convertBAM2BigWig. BSgenome package was made using the instruction https://bioconductor.org/packages/release/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf.
What could be the reason for the received warning and how can I fix it?

Best,
Liuaza

**Comment by MalteThodberg** [comment]
This does look a bit weird! The convertBAM2BigWig is (as the name docs would also suggest) only experimental at the moment, so use at your risk!

Looks like some issues with the genome-information stored in the seqinfo slot: Could you show the output of seqinfo(CTSSs), seqlevels(CTSSs) and seqlengths(CTSSs)?

**Comment by NexentaEL** [comment]
```
> seqinfo(CTSSs)
Seqinfo object with 2 sequences from ASM2216v1 genome:
  seqnames               seqlengths isCircular    genome
  NC_016856.1_chromosome    4870265      FALSE ASM2216v1
  NC_016855.1_plasmid         93832      FALSE ASM2216v1
> seqlevels(CTSSs)
[1] "NC_016856.1_chromosome" "NC_016855.1_plasmid"   
> seqlengths(CTSSs)
NC_016856.1_chromosome    NC_016855.1_plasmid 
               4870265                  93832 
```

But both chromosome and plasmid are circular, as I indicated in a dcf file for my custom BSgenome:
```
seqnames: c("NC_016856.1_chromosome", "NC_016855.1_plasmid")
circ_seqs: c("NC_016856.1_chromosome", "NC_016855.1_plasmid")
```

Initially, I didn't indicate circ_seqs in the dcf file but it was fixed before this question, and now I tried to completely delete this BSgenome data package and install it again but it didn't help. What else can I try?

**Comment by NexentaEL** [comment]
Thank you so much for the tip, I reinstalled BSgenome again and finally it worked without this warning message

**Comment by MalteThodberg** [comment]
Good to hear it's working! I will consider adding some more informative error messages for handling cases like this.

Again, I cannot stress this enough: I have not done much testing on convertBAM2BigWig yet, so I highly recommend doing lots of sanity checks that everything is working as expected!
